version: '3'

vars:

  HOST:
    sh: hostname

  USER:
    sh: whoami

tasks:

  gc:
    cmds:
      - nix store gc
      - sudo nix-collect-garbage

  update:
    cmds:
      - nix flake update

  test.system:
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} test

  build.system:
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} build

  switch.system:
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} switch

  build.home:
    cmds:
      - home-manager --flake .#gecko build

  switch.home:
    cmds:
      - home-manager --flake .#gecko switch

  switch.all:
    deps: [update]
    cmds: 
      - task: switch.system
      - task: switch.home
      - task: gc
