version: '3'

vars:

  HOST:
    sh: hostname

  USER:
    sh: whoami

tasks:

  gc:
    cmds:
      - nix store gc

  update:
    cmds:
      - nix flake update

  test.system:
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} test

  build.system:
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} build

  switch.system:
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} switch

  news.home:
    cmds:
      - nix run home-manager -- news

  build.home:
    cmds:
      - nix run home-manager -- --flake .#{{.HOST}} build

  switch.home:
    cmds:
      - nix run home-manager -- --flake .#{{.HOST}} switch

  switch.all:
    deps: [update]
    cmds: 
      - task: switch.system
      - task: switch.home
      - task: gc
