version: '3'

vars:

  HOST:
    sh: hostname

  USER:
    sh: whoami

tasks:

  gc:
    cmds:
      - nix store gc
      - sudo nix-collect-garbage

  update:
    cmds:
      - nix flake update

  system.test:
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} test

  system.switch:
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} switch

  home.build:
    cmds:
      - home-manager --flake .#gecko build

  home.switch:
    cmds:
      - home-manager --flake .#gecko switch
